### ISSUE TITLE
New accounts starting with 20 items in Collection

### ISSUE THREAD

**Issue by GrouchyPanda** [iamtravisw/amiiboland#5]
Started a new account, when i was finally able to login (not sure if the login has been busted for the last week or so as the page continued to redirect to the login page with no errors or anything showing) my profile said that I had collected 20/180, without me having added any items. I removed some that I indeed dont have, and added a handful more, but I have since stopped altering the collection so that if need be you can look into my account to see why there were 20 items in it.

Username: GrouchyPanda

**Comment by GrouchyPanda** [comment]
Also, the profile page itself is blank, other than the counter at top. Not sure if there is supposed to be a list or something on the "Collection/Favorites/Wish List" tabs

**Comment by GrouchyPanda** [comment]
Wishlist similarly has 17 items in it, and I have not added anyhting to this list

**Comment by iamtravisw** [comment]
Hi GrouchyPanda - I am looking into this for you. The Collection table does not show anything added for your UserID. I am going to wait for tonight's backup and then move a copy over to my dev environment to do more in depth testing. I will let you know what I find.

**Comment by iamtravisw** [comment]
Hi GrouchyPanda - I was unable to duplicate this on my dev environment or in production with a new account. I'm going close this as it does not seem to be widespread. When I pulled the data down from production, it was an exact copy from last night so I would have been able to see anything that you were seeing. If you're still having problems, can you email me at iamtravisw@gmail.com with screenshots?
